### ISSUE TITLE
RNN only carry first batch of hebb weight

### ISSUE THREAD

**Issue by indiejoseph** [uber-common/differentiable-plasticity#1]
Seems your implementation only carry first batch of hebb weight to the next step, so when the batch size more than one, how do you handle it?

```python
hebb = (1 - self.eta) * hebb + self.eta * torch.bmm(yin.unsqueeze(2), yout.unsqueeze(1))[0] # <---
```
https://github.com/uber-common/differentiable-plasticity/blob/master/simple/simple.py#L119

Thanks!

**Comment by ThomasMiconi** [comment]
The code is not batched. Batch size is always 1 in these programs.

Preliminary experiment in batched evaluations (on a different task) suggested that batching did not really preoduce better *performance* for a given wallclock time (though it did somewhat increase the number of evaluations per wallclock time). We may revisit this issue in the future.

**Comment by yunuskocyigit** [comment]
Hi Thomas, I am just curious. How did you solve the problem?
Or, you just executed it without batch.

**Comment by ThomasMiconi** [comment]
Yes, all experiments are run with no batching.

**Comment by yunuskocyigit** [comment]
Thanks
