### ISSUE TITLE
no module named pics_tosend

### ISSUE THREAD

**Issue by jwingit** [uber-common/differentiable-plasticity#2]
In testpics.py there are the two lines:
```
import pics_tosend as pics
from pics_tosend import Network
```
but the module "pics_tosend"  does not exist.

**Comment by ThomasMiconi** [comment]
Thanks for notifying us. We fixed this (it must actually import images.py).

**Comment by affogato** [comment]
In `images/testpics.py`, `images/plotresults.py` and `images/showcompletion_eta.py`, there is a similar issue, with the module `pics_eta`.

Is there a missing file, or is this also meant to be importing from `images.py` ?

Thanks

**Comment by ThomasMiconi** [comment]
The latter. We have fixed the files. Thanks for notifying us!
